package com.bookhup.model;

public enum ActionType {

    // AUTH
    AUTH_LOGIN,
    AUTH_LOGOUT,

    // USER
    USER_FOLLOW,
    USER_UNFOLLOW,

    // POST
    POST_CREATE,
    POST_UPDATE,
    POST_DELETE,
    POST_VIEW,
    POST_LIKE,
    POST_UNLIKE,
    POST_SHARE,
    POST_SAVE,
    POST_REPORT,
    POST_CLICK_IMAGE,
    POST_CLICK_COMMENT_SECTION,

    // COMMENT
    COMMENT_CREATE,
    COMMENT_REPLY,
    COMMENT_DELETE,
    COMMENT_LIKE,
    COMMENT_VIEW,

    // HASHTAG
    HASHTAG_CLICK,
    HASHTAG_FOLLOW,

    // BOOK
    BOOK_SEARCH,
    TAG_SEARCH,
    POST_STATS_VIEW,
    BOOK_VIEW,
    BOOK_VIEW_TRENDING,
    BOOK_VIEW_DETAIL,
    BOOK_READ_SAMPLE,
    BOOK_ADD_TO_FAVORITE,
    BOOK_REMOVE_FROM_FAVORITE,

    // REVIEW
    REVIEW_CREATE,
    REVIEW_UPDATE,
    REVIEW_DELETE,
    REVIEW_LIKE,
    REVIEW_UNLIKE,
    REVIEW_SHARE,
    REVIEW_VIEW,
    REVIEW_REPORT,

    // READING
    READING_ADD,
    READING_UPDATE,
    READING_VIEW,
    READING_PROGRESS_UPDATE,
    READING_FINISH_BOOK,

    // NOTIFICATION
    NOTIFICATION_VIEW,
    NOTIFICATION_CLICK;
}
