#Database Configuration
# ===============================
# = SERVER CONFIGURATION
# ===============================
server.port=8080

# ===============================
# = DATASOURCE (MariaDB)
# ===============================
spring.datasource.url=jdbc:mariadb://localhost:3306/book_hub?useUnicode=true&characterEncoding=utf8mb4&serverTimezone=Asia/Ho_Chi_Minh
spring.datasource.username=root
spring.datasource.password=1232001
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# ===============================
# = HIKARI CONNECTION POOL (Default in Spring Boot)
# ===============================
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=600000
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.pool-name=HikariCP

# ===============================
# = JPA / HIBERNATE
# ===============================
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect
spring.jpa.hibernate.ddl-auto=update
# Options:
# none        - do not create or modify schema
# validate    - only validate schema correctness
# update      - update schema based on entities (use during development)
# create      - drop and recreate schema every application startup
# create-drop - create schema on startup and drop on shutdown

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Optional: print SQL logs to console
# logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# ===============================
# = TIMEZONE
# ===============================
spring.jpa.properties.hibernate.jdbc.time_zone=Asia/Ho_Chi_Minh
# Hibernate Configuration
# Show or not log for each sql query
spring.main.allow-circular-references=true
# Hibernate ddl auto (create, create-drop, update): with "update" the database
# schema will be automatically updated accordingly to java entities found in
# the project
spring.webflux.cors.allowed-origins=https://taupe-licorice-bae4fb.netlify.app
spring.main.allow-bean-definition-overriding=true
multipart.enabled=true
spring.jackson.serialization.fail-on-empty-beans=false
# Allows Hibernate to generate SQL optimized for a particular DBMS
security.basic.enable: false
security.ignored=/**
#app.jwt-secret=daf66e01593f61a15b857cf433aae03a005812b31234e149036bcc8dee755dbb
#app-jwt-expiration-milliseconds=604800000

bookhub.app.jwtSecret= ======================bookHub=Spring===========================
bookHub.app.jwtExpirationMs=86400000

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=bookhub2526@gmail.com
spring.mail.password=ofqk deao wcae qgni
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# 15 minutes * 60 * 60
scheduler.hashtag.rate=900000

behavior-log.workers: 1
behavior-log.batch-size: 2

notification-push.workers: 1
notification-push.batch-size: 2
